#pragma once
#include "../Common/common.hpp"
/*
    GOAL, BE ABLE TO ASK FOR X AMOUNT OF BYTES FROM STACK, AND BE ABLE TO ASK TO REMOVE X BYTES FROM STACK.

    ASKING FOR X AMOUNT OF BYTES FROM STACK WILL RETURN A POINTER THAT CAN BE DEREFERANCED AND INTERPRETED ANY WAY.

*/
/*
    BOTH CLASSES WILL FOLLOW ENCAPSULATION DESIGN
*/

class MemoryInstance{
public:

private:
};
class MemoryFactory{
public:


private:

};
